const CREATE_POST = 'post:CREATE_POST';
const UPDATE_POST = 'post:UPDATE_POST';
const DELETE_POST = 'post:DELETE_POST';
const GET_PROF_POST = 'post:GET_PROF-POST';
const REPORT_POST = 'post:REPORT_POST';
const GETALL_POST = 'post:GETALL_POST';

module.exports={CREATE_POST,UPDATE_POST,DELETE_POST,GET_PROF_POST,REPORT_POST,GETALL_POST}