// SUPER ADMIN ONLY
const ADD_ADMIN ='admin:ADD_ADMIN';
const GET_ADMINS ='admin:GET_ADMINS';
const DELETE_ADMIN ='admin:DELETE_ADMIN';
// ADMIN & SUPER ADMIN
const GET_USERS ='admin:GET_USERS';
const GET_POSTS ='admin:GET_POSTS';
const REVIEW_REPORT ='admin:REVIEW_REPORT';
const BLOCK_POST ='admin:BLOCK_POST';
const BLOCK_USER ='admin:BLOCK_USER';




module.exports = {ADD_ADMIN,GET_ADMINS,DELETE_ADMIN,
    GET_USERS,GET_POSTS,REVIEW_REPORT,BLOCK_POST,BLOCK_USER}