const UPDATE_PROFILE = 'user:UPDATE_PROFILE';
const UPDATE_PASSWORD = 'user:UPDATE_PASSWORD';
const DEACTIVATE_ACC = 'user:DEACTIVATE_ACC';

module.exports={UPDATE_PROFILE,UPDATE_PASSWORD,DEACTIVATE_ACC}