const { ADD_ADMIN, GET_ADMINS, DELETE_ADMIN, GET_USERS, REVIEW_REPORT, BLOCK_USER, BLOCK_POST, GET_POSTS } = require("../../modules/admin/endPoints");
const { CREATE_ADV, UPDATE_ADV, DELETE_ADV, GET_ADV } = require("../../modules/adv/endPoints");

module.exports=[ADD_ADMIN,GET_ADMINS,DELETE_ADMIN,GET_USERS,GET_POSTS,REVIEW_REPORT,BLOCK_USER,BLOCK_POST,
CREATE_ADV,UPDATE_ADV,DELETE_ADV,GET_ADV]
